import { useDispatch, useSelector } from "react-redux";
import {
  toggleAssistant,
  addMessage,
  setAssistantStatus,
} from "../../store/assistantSlice";

import {
  updateCandidateStage,
  updateRubric,
  addAuditLog,
} from "../../store/recruiterSlice";

import AssistantAvatar from "./AssistantAvatar";
import { useState } from "react";

export default function AssistantPanel({ position }) {
  const dispatch = useDispatch();
  const [showScheduleModal, setShowScheduleModal] = useState(false);

  const assistant = useSelector((state) => state.assistant);
  const jobs = useSelector((state) => state.recruiter.jobs);

  if (!assistant.isOpen) return null;

  // Calculate optimal position based on button location
  const getPanelPosition = () => {
    const panelWidth = 320;
    const panelHeight = 384;
    const buttonSize = 56;
    const padding = 10;

    let left = position.x - panelWidth - padding;
    let top = position.y;

    // If button is on right side, open panel to the left
    if (position.x > window.innerWidth / 2) {
      left = position.x - panelWidth - padding;
    } else {
      // If button is on left side, open panel to the right
      left = position.x + buttonSize + padding;
    }

    // If button is on bottom, open panel upwards
    if (position.y > window.innerHeight / 2) {
      top = position.y - panelHeight + buttonSize;
    } else {
      // If button is on top, open panel downwards
      top = position.y;
    }

    // Clamp values to stay within viewport
    left = Math.max(0, Math.min(left, window.innerWidth - panelWidth));
    top = Math.max(0, Math.min(top, window.innerHeight - panelHeight));

    return { left, top };
  };

  const panelPos = getPanelPosition();

  const sendMessage = (text) => {
    if (!text.trim()) return;

    dispatch(
      addMessage({
        sender: "user",
        text,
        time: new Date().toLocaleTimeString(),
      })
    );

    dispatch(setAssistantStatus("thinking"));

    setTimeout(() => {
      handleCommand(text.toLowerCase());
    }, 700);
  };

  const handleCommand = (text) => {
    const job = jobs[0]; // demo purpose

    if (!job || !job.candidates) {
      reply("No job or candidates found. Please create a job with candidates first.");
      return;
    }

    // 1️⃣ Generate Rubric
    if (text.includes("generate") && text.includes("rubric")) {
      const rubric = [
        { id: "r1", label: "Communication Skills", weight: 25 },
        { id: "r2", label: "Technical Expertise", weight: 35 },
        { id: "r3", label: "Problem Solving", weight: 20 },
        { id: "r4", label: "Team Collaboration", weight: 15 },
        { id: "r5", label: "Experience Level", weight: 5 },
      ];

      dispatch(
        updateRubric({
          jobId: job.id,
          rubric: rubric,
        })
      );

      dispatch(
        addAuditLog({
          jobId: job.id,
          message: `Evaluation rubric auto-generated by AI: ${rubric.map(r => `${r.label} (${r.weight}%)`).join(", ")}`,
        })
      );

      reply("✅ Evaluation rubric generated! I've auto-filled 5 criteria with weighted scoring to match this role's requirements.");
      return;
    }

    // 2️⃣ Shortlist Top Candidates
    if (text.includes("shortlist") && text.includes("candidate")) {
      // Create a copy of candidates array before sorting to avoid mutation
      const topCandidates = [...job.candidates]
        .sort((a, b) => (b.score || 0) - (a.score || 0))
        .slice(0, 3);

      if (topCandidates.length === 0) {
        reply("No candidates found for this job.");
        return;
      }

      let shortlistedCount = 0;

      topCandidates.forEach((candidate) => {
        if (candidate.stage !== "Shortlisted") {
          dispatch(
            updateCandidateStage({
              jobId: job.id,
              candidateId: candidate.id,
              newStage: "Shortlisted",
            })
          );
          shortlistedCount++;
        }
      });

      const candidateNames = topCandidates.map(c => c.name).join(", ");
      const scores = topCandidates.map(c => `${c.name} (${c.score}%)`).join(", ");

      dispatch(
        addAuditLog({
          jobId: job.id,
          message: `Top ${shortlistedCount} candidates shortlisted by AI: ${candidateNames} with scores: ${scores}`,
        })
      );

      reply(`✅ Shortlisted ${shortlistedCount} top candidates: ${candidateNames}. They've all been moved to the Shortlisted stage based on their scores.`);
      return;
    }

    // 3️⃣ Schedule Interview
    if (text.includes("schedule") && text.includes("interview")) {
      setShowScheduleModal(true);
      reply("📅 Opening interview scheduler. Select a candidate and time slot to schedule their interview.");
      return;
    }

    // Helpful responses
    if (text.includes("hi") || text.includes("hello") || text.includes("hey")) {
      reply("👋 Hi! I can help you with recruitment tasks. Try asking me to:\n• 'Shortlist top candidates for this job'\n• 'Generate an evaluation rubric for this role'\n• 'Schedule interview'");
      return;
    }

    if (text.includes("help")) {
      reply("📋 Here's what I can do:\n1. **Shortlist candidates** - I'll rank and move top candidates to shortlisted stage\n2. **Generate rubric** - Auto-fill evaluation criteria with weights\n3. **Schedule interview** - Open the scheduling interface");
      return;
    }

    reply("I didn't quite understand that. Try asking me to shortlist candidates, generate a rubric, or schedule an interview.");
  };

  const reply = (text) => {
    dispatch(setAssistantStatus("speaking"));

    dispatch(
      addMessage({
        sender: "assistant",
        text,
        time: new Date().toLocaleTimeString(),
      })
    );

    setTimeout(() => {
      dispatch(setAssistantStatus("idle"));
    }, 500);
  };

  return (
    <div
      style={{
        position: "fixed",
        left: `${panelPos.left}px`,
        top: `${panelPos.top}px`,
        zIndex: 40,
      }}
      className="w-80 bg-white rounded-2xl shadow-2xl border border-gray-100 flex flex-col h-96 overflow-hidden"
    >
      {/* Header */}
      <div className="p-4 border-b border-gray-100 flex items-center justify-between flex-shrink-0 bg-gradient-to-r from-blue-600 via-blue-500 to-blue-600 text-white">
        <div className="flex items-center gap-3">
          <AssistantAvatar status={assistant.status} />
          <span className="font-bold text-lg">TalentSage AI</span>
        </div>
        <button
          onClick={() => dispatch(toggleAssistant())}
          className="text-xl hover:bg-blue-500 rounded-full p-1 transition-colors duration-200"
        >
          ✖
        </button>
      </div>

      {/* Messages - Scrollable */}
      <div className="flex-1 p-4 overflow-y-auto space-y-3 text-sm bg-gray-50">
        {assistant.messages.map((msg, i) => (
          <div
            key={i}
            className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-xs px-4 py-2 rounded-2xl break-words whitespace-pre-wrap ${
                msg.sender === "user"
                  ? "bg-blue-600 text-white rounded-br-none shadow-md"
                  : "bg-white text-gray-900 border-2 border-gray-200 rounded-bl-none"
              }`}
            >
              <p className="text-sm">{msg.text}</p>
              <span className={`text-xs block mt-1 ${
                msg.sender === "user" ? "text-blue-100" : "text-gray-400"
              }`}>
                {msg.time}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-100 flex-shrink-0 bg-white">
        <input
          placeholder="Ask TalentSage..."
          className="w-full border-2 border-gray-300 rounded-xl px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 placeholder-gray-400 hover:border-gray-400 transition-colors duration-200"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              sendMessage(e.target.value);
              e.target.value = "";
            }
          }}
        />
      </div>
    </div>
  );
}